name: Check if index.html exists

on: [push]

jobs:
  check-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Check for index.html
        run: |
          if [ ! -f "index.html" ]; then
            echo "index.html does not exist."
            exit 1
          else
            echo "index.html exists."
          fi